# Generated by Django 6.0.5 on 2026-05-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_price', models.FloatField()),
                ('Product_count', models.IntegerField()),
                ('Product_available', models.BooleanField()),
                ('Product_str', models.CharField(max_length=100)),
            ],
        ),
    ]
